FROM node:22.23.1

ARG SHOPIFY_API_KEY
ARG SHOPIFY_API_SECRET
ARG HOST
ARG SCOPES

ENV SHOPIFY_API_KEY=$SHOPIFY_API_KEY
ENV SHOPIFY_API_SECRET=$SHOPIFY_API_SECRET
ENV HOST=$HOST
ENV SCOPES=$SCOPES
EXPOSE 8081
WORKDIR /app
COPY web .
RUN npm install
RUN cd frontend && npm install && npm run build
CMD ["npm", "run", "serve"]
