# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a076a9af36e2033b90fd58de755d8184"
name = "pro-validation"
application_url = "https://example.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_validations,read_checkouts,read_orders"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[webhooks]
api_version = "2026-07"

[[webhooks.subscriptions]]
topics = [ "checkouts/create" ]
uri = "/api/webhooks"

[[webhooks.subscriptions]]
topics = [ "orders/create" ]
uri = "/api/webhooks"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
