# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c75f95407d38a8c327ec1fcef9b2e9cf"
name = "CheckoutIQ"
application_url = "https://showcase-overheat-cylinder.ngrok-free.dev"
embedded = true

[webhooks]
api_version = "2026-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_validations,read_checkouts,read_orders,write_delivery_customizations,read_delivery_customizations,write_payment_customizations,read_payment_customizations,read_shipping"

[auth]
redirect_urls = [ "https://showcase-overheat-cylinder.ngrok-free.dev/api/auth","https://showcase-overheat-cylinder.ngrok-free.dev/api/auth/callback" ]

[[webhooks.subscriptions]]
topics = [ "checkouts/create", "checkouts/update" ]
uri = "/api/webhooks"

[[webhooks.subscriptions]]
topics = [ "orders/create" ]
uri = "/api/webhooks"

[[webhooks.subscriptions]]
topics = [ "app/uninstalled" ]
uri = "/api/webhooks"

[build]
automatically_update_urls_on_dev = true
