query RunInput {
  discountNode {
    metafield(namespace: "ruleforge", key: "discount_rules") {
      value
    }
  }
  cart {
    cost {
      subtotalAmount {
        amount
        currencyCode
      }
    }
    buyerIdentity {
      customer {
        id
        metafield(namespace: "cart-validation", key: "metadata") {
          value
        }
      }
    }
    lines {
      id
      quantity
      cost {
        amountPerQuantity {
          amount
          currencyCode
        }
        totalAmount {
          amount
          currencyCode
        }
      }
      merchandise {
        ... on ProductVariant {
          id
          sku
          product {
            id
            vendor
            metafield(namespace: "cart-validation", key: "metadata") {
              value
            }
          }
        }
      }
    }
  }
}
